#!/bin/sh

NAME=$1

if [ $# != 1 ]; then
	echo "Need one argument (experiment name prefix)"
else
	scp CDAPdhlb@blp02.ccni.rpi.edu:/gpfs/u/home/CDAP/CDAPdhlb/scratch/delnetresults/\{"$NAME"_synapses.bin, "$NAME"_instarttimes.txt,"$NAME"_spikes.txt\} \
	/home/dahlbom/research/delnet/experiments

fi


